mod account_page;
pub mod components;
mod details_page;
pub mod macro_templates;
pub mod menu_page;
mod start;
pub mod templates;
mod categories_page;
pub use account_page::get_account_page;
pub use account_page::post_language;
pub use account_page::post_primary_language;
pub use details_page::get_details_data;
pub use details_page::get_details_home;
pub use details_page::post_details_home;
pub use menu_page::get_menu_page;
pub use menu_page::get_menu_item;
pub use menu_page::post_menu_item;
pub use menu_page::get_menu_item_details;
pub use start::get_start_page;
pub use categories_page::get_categories_page;
pub use categories_page::get_category_item;
pub use categories_page::post_category_item;
